### ISSUE TITLE
app crashes on start (Arch Linux)

### ISSUE THREAD

**Issue by bittin** [cosmic-utils/observatory#1]
luna@celestia ~/o/t/release (main)> ./observatory
thread 'main' panicked at src/app/applications.rs:23:52:
called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: Other { at: Valid(""), kind: Tag } }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by Adam-Cosner** [comment]
Hmm, that's odd. Do you have a /usr/share/applications directory?

**Comment by Adam-Cosner** [comment]
In any case, I added proper error handling for that now so could you test the latest commit on main?

**Comment by bittin** [comment]
@Adam-Cosner it works as it should now, closing this issue
also added a PR to add Swedish
