### ISSUE TITLE
vendoring

### ISSUE THREAD

**Issue by rrahl0** [cosmic-utils/observatory#17]
sadly, vendoring is not possible, as when I vendor, I get the error

```
found duplicate version of package `cosmic-protocols v0.1.0` vendored from two sources:
source 1: https://github.com/pop-os/cosmic-protocols?rev=c8d3a1c#c8d3a1c3
source 2: https://github.com/pop-os/cosmic-protocols.git#27d70b6e
```

as the maintainer of cosmic in openSUSE, it would be great if that could be fixed. (our buildsystem has no internet during build)

**Comment by Adam-Cosner** [comment]
Try it again with the latest commit and get back to me on it
