### ISSUE TITLE
[Bug] Cargo.toml not recognised in observatory-daemon when building

### ISSUE THREAD

**Issue by LiamillionSS** [cosmic-utils/observatory#23]
Tried compiling on Arch Linux 6.12.4-arch1-1 and it makes it all the way to the final build step where it encounters `error: manifest path `./src/observatory-daemon/Cargo.toml` does not exist` despite the file being exactly where its expected.

![image](https://github.com/user-attachments/assets/9e4ecfb2-4b34-451a-b9aa-d63dd5ebb584)
![image](https://github.com/user-attachments/assets/2c24937a-8e98-4ab1-9b4f-c0fe3bb1d707)

Is this a bug or a just matter of the release not being intended for Arch as per "for both Pop_OS! 24.04 alpha and Fedora 39+"?

**Comment by Adam-Cosner** [comment]
Ah, I messed up on the justfile, let me fix that real quick

**Comment by Adam-Cosner** [comment]
Alright, should be working now
